# Generated by Django 6.0.4 on 2026-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('student', 'Student'), ('intern', 'Intern'), ('junior', 'Junior'), ('mid', 'Mid-level'), ('senior', 'Senior')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('student', 'Student'), ('recruiter', 'Recruiter'), ('company', 'Company'), ('admin', 'Admin')], default='jobseeker', max_length=20),
        ),
    ]
