# Generated by Django 6.0.4 on 2026-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
       
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
