# Generated by Django 6.0.4 on 2026-05-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_applicant_candidatenote'),
        ('applications', '0003_application_reviewed_at'),
    ]

    operations = [
    ]
