# Generated by Django 6.0.4 on 2026-05-16 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_merge_20260514_1418'),
        ('jobs', '0004_alter_job_job_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job', 'status'], name='application_job_id_7836e3_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['reviewed_at'], name='application_reviewe_5ce821_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatenote',
            index=models.Index(fields=['candidate', 'recruiter'], name='application_candida_092f32_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatenote',
            index=models.Index(fields=['created_at'], name='application_created_f57caa_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('job__isnull', False)), fields=('job', 'applicant'), name='unique_application_per_job_applicant'),
        ),
    ]
