# Generated by Django 5.1.4 on 2026-05-03 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='incomplete', max_length=20)),
                ('completion_percentage', models.IntegerField(default=0)),
                ('has_name', models.BooleanField(default=False)),
                ('has_email', models.BooleanField(default=False)),
                ('has_phone', models.BooleanField(default=False)),
                ('has_location', models.BooleanField(default=False)),
                ('has_bio', models.BooleanField(default=False)),
                ('has_skills', models.BooleanField(default=False)),
                ('has_experience_level', models.BooleanField(default=False)),
                ('has_education', models.BooleanField(default=False)),
                ('has_desired_roles', models.BooleanField(default=False)),
                ('has_gender', models.BooleanField(default=False)),
                ('has_profile_photo', models.BooleanField(default=False)),
                ('has_linkedin', models.BooleanField(default=False)),
                ('has_resume', models.BooleanField(default=False)),
                ('has_portfolio', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
