# Generated by Django 6.0.4 on 2026-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], default='full_time', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations'), ('hr', 'HR'), ('finance', 'Finance'), ('product', 'Product')], default='', max_length=20)),
                ('description', models.TextField()),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career_level', models.CharField(blank=True, choices=[('Entry Level', 'Entry Level'), ('Mid Level', 'Mid Level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('requirements', models.TextField(blank=True)),
                ('years_experience', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('recruiter', 'Recruiter'), ('seed', 'Seed'), ('scraped', 'Scraped')], default='recruiter', max_length=20)),
                ('is_filled', models.BooleanField(default=False)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
