# Generated by Django 6.0.4 on 2026-05-01 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('salary_min', models.FloatField(blank=True, null=True)),
                ('salary_max', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('job_type', models.CharField(blank=True, max_length=50)),
                ('logo', models.URLField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'job_id')},
            },
        ),
    ]
