# Generated by Django 6.0.4 on 2026-05-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_career_level_job_category_job_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('on_site', 'On-site'), ('hybrid', 'Hybrid')], default='full_time', max_length=20),
        ),
    ]
