# Generated by Django 6.0.4 on 2026-05-01 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=200)),
                ('country', models.CharField(default='uae', max_length=50)),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('job_type', models.CharField(blank=True, max_length=50)),
                ('salary_min', models.FloatField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('apply_link', models.URLField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.jobalert')),
            ],
            options={
                'ordering': ['-matched_at'],
                'unique_together': {('alert', 'job_id')},
            },
        ),
    ]
