@echo off
echo Building frontend...
call npm run build

echo Installing backend dependencies...
call venv\Scripts\pip install -r requirements.txt

echo Running migrations...
call venv\Scripts\python manage.py migrate --noinput

echo Starting server...
venv\Scripts\daphne -b 0.0.0.0 -p 8000 hireflow.asgi:application
