# Generated by Django 6.0.4 on 2026-05-16 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stages', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('engaged', 'Engaged'), ('interviewing', 'Interviewing'), ('offered', 'Offered'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('inactive', 'Inactive')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('job_board', 'Job Board'), ('recruiter', 'Recruiter'), ('event', 'Event'), ('cold_email', 'Cold Email'), ('other', 'Other')], default='website', max_length=20)),
                ('source_details', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=0, help_text='1-5 rating')),
                ('is_active', models.BooleanField(default=True)),
                ('last_contacted', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidatePipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('stage_order', models.IntegerField(default=0)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('moved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_candidates', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stages', to='candidate_crm.candidatepipeline')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='candidate_crm.candidateprofile')),
            ],
            options={
                'ordering': ['pipeline', 'stage_order', 'entered_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone Call'), ('meeting', 'Meeting'), ('interview', 'Interview'), ('note', 'Note'), ('task', 'Task'), ('application', 'Application'), ('offer', 'Offer'), ('rejection', 'Rejection')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('attendees', models.JSONField(default=list)),
                ('outcome', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interactions', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='candidate_crm.candidateprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('is_read', models.BooleanField(default=False)),
                ('thread_id', models.CharField(blank=True, max_length=255)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='candidate_crm.candidateprofile')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('portfolio', 'Portfolio'), ('transcript', 'Transcript'), ('certificate', 'Certificate'), ('contract', 'Contract'), ('offer_letter', 'Offer Letter'), ('nda', 'NDA'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='candidate_documents/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidate_crm.candidateprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('profile_view', 'Profile View'), ('document_download', 'Document Download'), ('email_sent', 'Email Sent'), ('email_received', 'Email Received'), ('task_completed', 'Task Completed'), ('status_change', 'Status Change'), ('note_added', 'Note Added'), ('interview_scheduled', 'Interview Scheduled'), ('offer_made', 'Offer Made')], max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_activities', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='candidate_crm.candidateprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('referral', 'Referral'), ('colleague', 'Colleague'), ('manager', 'Manager'), ('mentor', 'Mentor'), ('friend', 'Friend'), ('family', 'Family'), ('client', 'Client'), ('vendor', 'Vendor')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='candidate_crm.candidateprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relationships', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_tasks', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='candidate_crm.candidateprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_candidate_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['status', 'assigned_to'], name='candidate_c_status_1a02c9_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['source'], name='candidate_c_source_f759ab_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['rating'], name='candidate_c_rating_ee0021_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatepipelinestage',
            index=models.Index(fields=['pipeline', 'stage'], name='candidate_c_pipelin_80310e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatepipelinestage',
            index=models.Index(fields=['candidate', 'entered_at'], name='candidate_c_candida_18a566_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatepipelinestage',
            unique_together={('candidate', 'pipeline')},
        ),
        migrations.AddIndex(
            model_name='candidateinteraction',
            index=models.Index(fields=['candidate', 'date'], name='candidate_c_candida_07d107_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateinteraction',
            index=models.Index(fields=['interaction_type'], name='candidate_c_interac_d1af9c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateinteraction',
            index=models.Index(fields=['created_by'], name='candidate_c_created_ae4c12_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemail',
            index=models.Index(fields=['candidate', 'sent_at'], name='candidate_c_candida_63f917_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemail',
            index=models.Index(fields=['direction'], name='candidate_c_directi_d7fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemail',
            index=models.Index(fields=['thread_id'], name='candidate_c_thread__a5800c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedocument',
            index=models.Index(fields=['candidate', 'document_type'], name='candidate_c_candida_f4e66c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedocument',
            index=models.Index(fields=['uploaded_by'], name='candidate_c_uploade_21af2d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['candidate', 'created_at'], name='candidate_c_candida_2ea4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['activity_type'], name='candidate_c_activit_5c954a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['user', 'created_at'], name='candidate_c_user_id_ea7237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidaterelationship',
            unique_together={('candidate', 'related_user')},
        ),
        migrations.AddIndex(
            model_name='candidatetask',
            index=models.Index(fields=['candidate', 'status'], name='candidate_c_candida_729525_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatetask',
            index=models.Index(fields=['assigned_to', 'status'], name='candidate_c_assigne_d9f860_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatetask',
            index=models.Index(fields=['priority', 'due_date'], name='candidate_c_priorit_35b195_idx'),
        ),
    ]
