# Generated by Django 6.0.4 on 2026-05-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateinteraction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatepipeline',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatepipelinestage',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatepipelinestage',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_stages', to='candidate_crm.candidatepipeline'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crm_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatepipelinestage',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_stages', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateinteraction',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateemail',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidatedocument',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidateactivity',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidaterelationship',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidaterelationship',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidaterelationship',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_relationships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatetag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatetask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatetask',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='candidate_crm.candidateprofile'),
        ),
        migrations.AddField(
            model_name='candidatetask',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_candidate_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['status', 'assigned_to'], name='candidate_c_status_1a02c9_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['source'], name='candidate_c_source_f759ab_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['rating'], name='candidate_c_rating_ee0021_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatepipelinestage',
            index=models.Index(fields=['pipeline', 'stage'], name='candidate_c_pipelin_80310e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatepipelinestage',
            index=models.Index(fields=['candidate', 'entered_at'], name='candidate_c_candida_18a566_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatepipelinestage',
            unique_together={('candidate', 'pipeline')},
        ),
        migrations.AddIndex(
            model_name='candidateinteraction',
            index=models.Index(fields=['candidate', 'date'], name='candidate_c_candida_07d107_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateinteraction',
            index=models.Index(fields=['interaction_type'], name='candidate_c_interac_d1af9c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateinteraction',
            index=models.Index(fields=['created_by'], name='candidate_c_created_ae4c12_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemail',
            index=models.Index(fields=['candidate', 'sent_at'], name='candidate_c_candida_63f917_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemail',
            index=models.Index(fields=['direction'], name='candidate_c_directi_d7fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateemail',
            index=models.Index(fields=['thread_id'], name='candidate_c_thread__a5800c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedocument',
            index=models.Index(fields=['candidate', 'document_type'], name='candidate_c_candida_f4e66c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatedocument',
            index=models.Index(fields=['uploaded_by'], name='candidate_c_uploade_21af2d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['candidate', 'created_at'], name='candidate_c_candida_2ea4f3_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['activity_type'], name='candidate_c_activit_5c954a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateactivity',
            index=models.Index(fields=['user', 'created_at'], name='candidate_c_user_id_ea7237_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidaterelationship',
            unique_together={('candidate', 'related_user')},
        ),
        migrations.AddIndex(
            model_name='candidatetask',
            index=models.Index(fields=['candidate', 'status'], name='candidate_c_candida_729525_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatetask',
            index=models.Index(fields=['assigned_to', 'status'], name='candidate_c_assigne_d9f860_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatetask',
            index=models.Index(fields=['priority', 'due_date'], name='candidate_c_priorit_35b195_idx'),
        ),
    ]
