# Generated by Django 6.0.4 on 2026-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0)),
                ('skill_match_score', models.FloatField(default=0.0)),
                ('experience_match_score', models.FloatField(default=0.0)),
                ('education_match_score', models.FloatField(default=0.0)),
                ('salary_match_score', models.FloatField(default=0.0)),
                ('location_match_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('match_reasons', models.JSONField(default=list)),
                ('missing_requirements', models.JSONField(default=list)),
                ('is_recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('experience_years', models.FloatField(default=0)),
                ('education_level', models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='bachelor', max_length=50)),
                ('preferred_locations', models.JSONField(default=list)),
                ('expected_salary_min', models.IntegerField(blank=True, null=True)),
                ('expected_salary_max', models.IntegerField(blank=True, null=True)),
                ('job_types', models.JSONField(default=list)),
                ('industries', models.JSONField(default=list)),
                ('resume_text', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_skills', models.JSONField(default=list)),
                ('experience_required', models.FloatField(default=0)),
                ('education_required', models.CharField(choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='bachelor', max_length=50)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('locations', models.JSONField(default=list)),
                ('job_types', models.JSONField(default=list)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description_weighted_keywords', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('applied', 'Applied'), ('saved', 'Saved'), ('rejected', 'Rejected'), ('interviewed', 'Interviewed'), ('hired', 'Hired')], max_length=20)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-action_date'],
            },
        ),
        migrations.CreateModel(
            name='MatchingAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('algorithm_type', models.CharField(choices=[('keyword', 'Keyword Based'), ('ml', 'Machine Learning'), ('hybrid', 'Hybrid')], default='hybrid', max_length=50)),
                ('weights', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
