# Generated by Django 6.0.4 on 2026-05-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_matching', '0002_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='candidate_matching.candidateprofile'),
        ),
        migrations.AddField(
            model_name='jobrequirement',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_requirement', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='candidate_matching.candidateprofile'),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='jobs.job'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatematch',
            unique_together={('candidate', 'job')},
        ),
    ]
